### PR TITLE
Create IdentityCore.podspec

### PR DESCRIPTION
**Pull request by zkrige**
Add CocoaPods functionality

### CODE REVIEW

**Comment by oldalton** [comment]
Thanks a lot for your contribution @zkrige.
However, Identity core is not meant to be used as a separate component. It's only meant to be used through ADAL and MSAL. ADAL already has its own Cocoapods and MSAL can be used with Carthage.

**Comment by zkrige** [comment]
Thank you for your comment. Yes I am aware I can use Carthage, but we have a strict policy to only use Cocoapods. I see no harm in providing both Carthage and Cocoapods support.

There were requests on MSAL repo to implement Cocoapods support, so I put this podspec together. I am personally using it in production and thought I could share it with the project

**Comment by oldalton** [comment]
I see, thanks for explanation @zkrige! I think you confused this repository with MSAL repository over here: https://github.com/AzureAD/microsoft-authentication-library-for-objc. This repository just contains common code for both MSAL and ADAL.

**Comment by oldalton** [comment]
@zkrige There's a submodule flag in CocoaPods: https://guides.cocoapods.org/making/specs-and-specs-repo.html 

in the source part in the podspec:  

s.source		 = {
  	:git => "<path/to/repo>",
  	:tag => s.version.to_s,
  	:submodules => true
  }

**Comment by zkrige** [comment]
Thanks so much for this. I *did* try this on the MSAL podspec, but it seemed to have no effect, so I ended up making 2 pods.

Let me try this again on MSAL podspec and see if i can make it work

**Comment by zkrige** [comment]
I've managed to hack my own MSAL podspec that submodule imports IdentityCore, but its extremely brittle due to direct filename references and similar.

A better solution would be to have IdentityCore as a self contained Cocoapod that could be reference from MSAL

Here is my podspec which works (for now), but I fully expect it to break in the future

```Pod::Spec.new do |s|
  s.name             = 'MSAL'
  s.version          = '0.1.2'
  s.summary          = 'Microsoft Authentication Library for iOS'
  s.description      = <<-DESC
The MSAL library preview for iOS gives your app the ability to begin using the Microsoft Cloud by supporting Microsoft Azure Active Directory and Microsoft Accounts in a converged experience using industry standard OAuth2 and OpenID Connect. The library also supports Microsoft Azure B2C for those using our hosted identity management service.
                       DESC

  s.homepage         = 'https://github.com/AzureAD/microsoft-authentication-library-for-objc'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Zayin Krige' => 'zkrige@gmail.com' }
  s.source           = { :git => 'https://github.com/zkrige/microsoft-authentication-library-for-objc.git', 
                         :submodules => true
			}
  s.ios.deployment_target = '10.0'

  s.source_files = 'MSAL/src/**/*.{h,m}', 
                   'MSAL/IdentityCore/IdentityCore/src/**/*.{h,m}', 
                   'MSAL/IdentityCore/IdentityCore/tests/**/MSIDVersion.{h,m,c}' 
  s.exclude_files = 'MSAL/src/cache/mac/**/*',
		    'MSAL/src/ui/mac/**/*',
		    'MSAL/src/public/mac/**/*',
		    'MSAL/src/MSIDVersion.m',
		    'MSAL/IdentityCore/IdentityCore/src/**/MSIDTestIdTokenUtil.{h,m}' 
  s.public_header_files = 'MSAL/src/public/*.h'
  s.prefix_header_file = 'MSAL/src/MSAL.pch'
  pch_MSAL = <<-EOS
	#import "NSDictionary+MSIDExtensions.h"
	#import "NSString+MSIDExtensions.h"
	#import "NSURL+MSIDExtensions.h"
	#import "MSIDLogger+Internal.h"
	#import "MSIDError.h"
	#import "MSIDOAuth2Constants.h"
	#import "IdentityCore_Internal.h"
	#import "MSAL_Internal.h"
	#import "NSOrderedSet+MSALExtensions.h"
	#import "MSALTokenCache.h"
	#import "MSALAccessTokenCacheItem.h"
	#import "MSALKeychainTokenCache.h"
	#import "MSALClientInfo.h"
  EOS
  s.prefix_header_contents = pch_MSAL
end```

**Comment by oldalton** [comment]
This is now supported natively in MSAL ObjC

**Pull request closed without merging**
