### PR TITLE
refresh_in assignment - do not merge

### PR DESCRIPTION
**Pull request by Veena11**
refresh_in assignment - WIP
Code not tested, test cases yet to be added.
Telemetry events yet to be added in SilentTokenRequest Flow

## Proposed changes

“refresh_in” will be communicated to the client library (MSAL) as part of the token response for the following grant_types supported by MSAL Obj-C:
o	authorization_code
o	refresh_token 
•	this will be added as a time in seconds at which MSAL should attempt to refresh the token
•	Refresh Attempt failure:
o	If an attempt to refresh an unexpired token fails, then simply return the existing token
o	If an attempt to refresh an expired token fails as a result of service being unavailable, then return extended lifetime access token if extended lifetime access enabled. (No change in current behavior)
.

## Type of change

- [ ] Feature work
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)

### CODE REVIEW

**Comment by NerevarineRule** [comment]
Hi @Veena11 
Happy new year. Thank you for making contributions to our library.
I have noticed that you haven't yet implemented the unit test. a colleague of mine from another team is working on a related feature and wanted to ask if you plan to finish this feature by completing the unit test in the near future. 

Thank you,
Peter

**Comment by Veena11** [comment]
Hi Peter,

I didnt have a system with mac OS to have my changes tested. That is the
reason I didnt work on the unit test. I might not able to get to it for
another month or so.

Regards
Veena

**Comment by kaisong1990** [comment]
@Veena11 Could we close this one?

**Comment by Veena11** [comment]
Changes merged in Pr : https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/975. Hence closing this PR.

**Pull request closed without merging**
