### PR TITLE
Allow customization of the SFSafariViewController's modalPresentationStyle

### PR DESCRIPTION
**Pull request by colinhumber**

### CODE REVIEW

**Comment by oldalton** [comment]
Thank you for the PR. Would it also make sense to apply same customization for embedded webview? @unpluggedk FYI

**Comment by colinhumber** [comment]
@oldalton Oh yes, absolutely. I had that change in the main MSAL project but forgot to migrate it over here. I'll add that as well.

**Comment by unpluggedk** [comment]
@colinhumber THanks for the PR, this seems like a very valuable enhancement!

**Comment by colinhumber** [comment]
@unpluggedk For sure! I've got the associated fix ready in https://github.com/AzureAD/microsoft-authentication-library-for-objc when this is merged.

**Pull request merged**
